"""add extraction_logs table

Revision ID: 8b4fd2dc3656
Revises: 
Create Date: 2026-05-14 21:44:40.485991+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4fd2dc3656'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('entities_found', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_logs_id'), 'extraction_logs', ['id'], unique=False)
    op.create_table('facciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('lugares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('razas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('raza_id', sa.Integer(), nullable=True),
    sa.Column('lugar_origen_id', sa.Integer(), nullable=True),
    sa.Column('faccion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faccion_id'], ['facciones.id'], ),
    sa.ForeignKeyConstraint(['lugar_origen_id'], ['lugares.id'], ),
    sa.ForeignKeyConstraint(['raza_id'], ['razas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artefactos_magicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('portador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portador_id'], ['personajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artefactos_magicos')
    op.drop_table('personajes')
    op.drop_table('razas')
    op.drop_table('lugares')
    op.drop_table('facciones')
    op.drop_index(op.f('ix_extraction_logs_id'), table_name='extraction_logs')
    op.drop_table('extraction_logs')
    # ### end Alembic commands ###
